### ISSUE TITLE
No highlighting for `const`

### ISSUE THREAD

**Issue by foxbunny** [somebee/vscode-imba#1]
![image](https://user-images.githubusercontent.com/65413/48868404-bc70df00-edd9-11e8-8939-d5d3e74b3936.png)

**Comment by aalemayhu** [comment]
This has been resolved in master thanks to 975acd6ceb33 (feat(var): Highlight const declarations as vars, 2019-08-27). I am just going to add the SFC syntax support before making a new release.

Thanks.
